### ISSUE TITLE
Error with node install

### ISSUE THREAD

**Issue by radwane-h** [peter-murray/node-teamcity-api#1]
Hi,

npm install fail for me with an untar error (npm version 3.3.12), 
I attached the log file for more details : 
[npm-debug.txt](https://github.com/peter-murray/node-teamcity-api/files/81520/npm-debug.txt)

**Comment by peter-murray** [comment]
It's an issue with the nock tests having invalid characters in the path under Windows.

I have excluded them from the `0.0.3` release, so that should get you past that error.
