### ISSUE TITLE
Add License

### ISSUE THREAD

**Issue by austinlparker** [peter-murray/node-teamcity-api#15]
Would it be possible to add a license to this project such as MIT or Apache?

**Comment by peter-murray** [comment]
https://github.com/peter-murray/node-teamcity-api/blob/master/package.json#L16

**Comment by austinlparker** [comment]
Oh, missed it because there wasn't a license.md. Thanks.

**Comment by peter-murray** [comment]
No problems, thought I had not pushed it there for a moment
