### ISSUE TITLE
Handle CORS Requests to TeamCity

### ISSUE THREAD

**Issue by kornatzky** [peter-murray/node-teamcity-api#19]
When adding CORS support to TeamCity, using the instructions in:[CORS Support](https://confluence.jetbrains.com/display/TCD10/REST+API#RESTAPI-CORSSupport)

We need to make this change in lib/request.js, line 64:

`    urlSuffix = "/app/rest/latest";`

We are creating a new branch, and wil do a pull request later.

**Comment by peter-murray** [comment]
This has been merged into master, will be present in a new release > 0.8
