### ISSUE TITLE
are you looking for help with maintaining this module?

### ISSUE THREAD

**Issue by mreinstein** [peter-murray/node-teamcity-api#28]
I'm happy to volunteer. Some ideas on changes I'd like to pursue:

* upgrade some dependencies (npm is throwing critical vulnerability warnings when installing this package)
* update to es6/modules

Just let me know, happy to send some PRs if these things are wanted.

thanks for a great module btw! ❤️

**Comment by mreinstein** [comment]
@peter-murray I'm still open to assisting with maintaining this module if that's something you'd be ok with. There are vulnerable dependencies that are in need of updates.

**Comment by peter-murray** [comment]
There are no vulnerable dependencies that need any attention that I know of. The development is being done off the `4.x` and `typescript` branches and I will be merging the latter one into main once I finish the docs so I can release that.

The `typescript` branch is already supporting the ES modules as being built from TypeScript and I have done some testing with users that were interested in using this (along with some simple testing on my part).

Can you possibly elaborate on what dependencies you see as being vulnerable?

The next big chunk of work will be adopting support for the new v2 REST API and I am happy to get some collaboration/help on that if you are interested.

**Comment by mreinstein** [comment]
> Can you possibly elaborate on what dependencies you see as being vulnerable?

When I run `npm audit` I see several vulnerabilities all pointing back to the `teamcity-rest-api`:

<img width="776" alt="Screen Shot 2022-01-18 at 8 49 17 AM" src="https://user-images.githubusercontent.com/718067/149981651-395a3f1f-7388-491e-aad1-d87c5c202393.png">


The npm module hasn't had a new version published in the last 5 years: https://www.npmjs.com/package/teamcity-rest-api
Can you publish a new version of this module to npm?

**Comment by mreinstein** [comment]
Also, all of the tests fail when I do `npm install` followed by `npm test`:

```
56) vcsRoots
       #delete()
         "before each" hook for "should delete a VCS Root":
     Error: Nock: No match for request {
  "method": "post",
  "url": "http://localhost:8111/app/rest/latest/vcs-roots",
  "headers": {
    "accept": "application/json, text/plain, */*",
    "content-type": "application/json",
    "user-agent": "axios/0.18.1",
    "content-length": 706,
    "authorization": "Basic cG11cnJheTpwYXNzd29yZA=="
  },
  "body": "{\"project\":{\"id\":\"_Root\"},\"name\":\"TestDeleteVcsRoot\",\"vcsName\":\"jetbrains.git\",\"properties\":{\"property\":[{\"name\":\"agentCleanFilesPolicy\",\"value\":\"ALL_UNTRACKED\"},{\"name\":\"agentCleanPolicy\",\"value\":\"ON_BRANCH_CHANGE\"},{\"name\":\"authMethod\",\"value\":\"PRIVATE_KEY_DEFAULT\"},{\"name\":\"branch\",\"value\":\"refs/heads/master\"},{\"name\":\"ignoreKnownHosts\",\"value\":\"true\"},{\"name\":\"push_url\",\"value\":\"git@github.com:someorg/dummy-repo.git\"},{\"name\":\"submoduleCheckout\",\"value\":\"CHECKOUT\"},{\"name\":\"teamcity:branchSpec\",\"value\":\"+:refs/heads/(*)\\n+:refs/(pull/*/merge)\"},{\"name\":\"url\",\"value\":\"https://github.com/someorg/dummy-repo.git\"},{\"name\":\"useAlternates\",\"value\":\"true\"},{\"name\":\"usernameStyle\",\"value\":\"USERID\"}]}}"
}
      at InterceptedRequestRouter.startPlayback (node_modules/nock/lib/intercepted_request_router.js:307:21)
      at InterceptedRequestRouter.handleEnd (node_modules/nock/lib/intercepted_request_router.js:160:12)
      at OverriddenClientRequest.req.end (node_modules/nock/lib/intercepted_request_router.js:77:33)
      at /Users/mike/Sites/node-teamcity-api/node_modules/follow-redirects/index.js:117:20
      at InterceptedRequestRouter.handleWrite (node_modules/nock/lib/intercepted_request_router.js:128:9)
      at OverriddenClientRequest.req.write (node_modules/nock/lib/intercepted_request_router.js:76:35)
      at RedirectableRequest.write (node_modules/follow-redirects/index.js:93:26)
      at RedirectableRequest.end (node_modules/follow-redirects/index.js:116:8)
      at dispatchHttpRequest (node_modules/axios/lib/adapters/http.js:235:11)
      at new Promise (<anonymous>)
      at httpAdapter (node_modules/axios/lib/adapters/http.js:18:10)
      at dispatchRequest (node_modules/axios/lib/core/dispatchRequest.js:59:10)
```

 Is there some other way that I'm supposed to invoke the tests, or are they just broken?

**Comment by peter-murray** [comment]
Sorry my bad on this and the response above, I crossed repository boundaries and did not notice when penning that response 🤦

Everything you have stated is indeed accurate. The updating of the vulnerable dependencies can be quickly solved, but there may be some changes in the underlying APIs that are not catered for.

I think the TeamCity API has probably moved quite a bit and I no longer use TeamCity, along with other changes they made towards using kotlin as the language for providing this type of automation.

If there is some valid use case and desire to keep this library alive, then I am happy to support that effort. As for the tests, nock was used to capture the outputs from a TC server some years back and to be able to replay the collected end to end data for the tests. I would have to take a deeper look into the tests and the failures, but it does require some objects to exist in a pre-configured TC (I was using a container for this locally with a persistent volume) if nock has not got he data for that request.

**Comment by mreinstein** [comment]
Oh haha, all good. I know the feeling of work sprawling across many repos. :)  That definitely makes more sense because I didn't see any feature branches in here related to typescript.

Yeah the teamcity stuff changes frequently; they seem to experiment with new UIs on a yearly basis.

I can't speak to other's use cases but in mine I'm just using this library to poll teamcity for in progress builds as part of my deploy process. It's all written in node/javascript so porting it to kotlin isn't something I'll pursue.

Passing unit tests would be nice but definitely not critical.

I could try to upgrade just the deps, test locally and send a PR if that would be something you're open to.

thanks for everything!

**Comment by mreinstein** [comment]
#29

**Comment by peter-murray** [comment]
So I remember what the problems were with the tests, nock has some issues with booleans and case on some of the data that it replays. This is not working currently due to these problems, but the data is accurate and the test valid once I fix the issues with nock.

I have released a `0.1.0-beta` to npm that contains the updates you provided and this is under the `next` rather than `latest` tag in npm for now so that you can report that it still works for you before I flip the `latest` npm tag.

**Comment by mreinstein** [comment]
I've pulled down the `0.1.0-beta` version in my app, I'll report results here next time I deploy. Thanks again!

**Comment by mreinstein** [comment]
I just did a production deploy with `node-teamcity-api@0.1.0-beta` and it seems to work without any issues. Thanks again!

**Comment by mreinstein** [comment]
still running the beta in prod. If you want to promote to 0.1.0 I'm convinced it works.  :D
