### ISSUE TITLE
Repository layout excludes development on Windows

### ISSUE THREAD

**Issue by jshumaker-accusoft** [peter-murray/node-teamcity-api#5]
Currently 2 major problems with repository preclude anyone on Windows from cloning the repo and trying to contribute.
1. Directories with identical names, but different case. test/nock/Projects test/nock/projects.
2. Use of <> characters in filenames.

test/nock/projects/getParameters/shouldgettheparametersofthe<Rootproject>

test/nock/projects/setParameter/shouldsetparameter'myTestValue'on<Rootproject>

Both work fine if working in Linux, but if trying to clone on windows, #1 causes the directories to get merged together and some unexpected behavior. Even on Linux it's a bit confusing to see and not recommended to do. 

The second prevents the checkout from happening at all with an unable to create file error.

I'm not sure if the current set up is a requirement of using nock or not, but I hope not as both are generally not a good idea to do anyways.

**Comment by peter-murray** [comment]
Nock is just outputting the names of the tests as strings, hence the issue. I understand the issue and the problem for Windows users, I develop on a Mac but spend my day on Windows.

It is a problem that needs sorting, but I have not finished working on the library, and it is on my list to resolve. Thanks for your interest, I will try to get some time this weekend to patch it for it to work under Windows.

**Comment by jshumaker-accusoft** [comment]
Much appreciated. I like very much what I see so far for the library and appreciate all the work you've put into it. Definitely not a high priority issue as it doesn't affect use, so this can certainly wait.

**Comment by peter-murray** [comment]
I still need to sort this, I will take a stab at it this weekend.

**Comment by peter-murray** [comment]
I think I have this corrected now under the master branch. Can you please give it a quick check and confirm or point out what is still broken? I just published this as version 0.0.4, which includes your other pull requests.

Thanks

**Comment by jshumaker-accusoft** [comment]
Repository clones and tests pass successfully on Windows, many thanks!
