### ISSUE TITLE
Add License

### ISSUE THREAD

**Issue by jshumaker-accusoft** [peter-murray/node-teamcity-api#7]
Project could use a license, both defined in package.json and a LICENSE file. Right now assuming you intend this to be open source and usable by others, but without a license we technically don't have the legal right to use it. It'd also make my company more comfortable with me contributing.

**Comment by peter-murray** [comment]
No problems, yes, it will be open source, any license you prefer more than others?

I will sort this out this weekend.

**Comment by jshumaker-accusoft** [comment]
[MIT](https://spdx.org/licenses/MIT.html) and [BSD 2-Clause](https://spdx.org/licenses/BSD-2-Clause.html) are both fairly permissive and common choices.

**Comment by peter-murray** [comment]
I added MIT, as per request.
